Universe           = vanilla
Initialdir         = /sphenix/user/mitrankova/macros/TrackingProduction
Executable         = $(Initialdir)/run_reco.sh
#Output             = /sphenix/user/mitrankova/macros/TrackingProduction/log/OO_spped_test_Masha_$(process).out
#Error             = /sphenix/user/mitrankova/macros/TrackingProduction/log/pp_$(process).err
Log                = /sphenix/user/mitrankova/macros/TrackingProduction/log/pp_TrackResid_$(process).log
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 8GB
#request_cpus       = 4
Priority           = 20
job_lease_duration = 3600
Arguments          = 100 $(process) 0
Queue 100
