Universe           = vanilla
Initialdir         = /sphenix/user/mitrankova/macros/TpcProduction
Executable         = $(Initialdir)/run_reco_match.sh
#Output            = /sphenix/user/mitrankova/macros/TpcProduction/log/pp_TpcReco_$(process).out
#Error             = /sphenix/user/mitrankova/macros/TpcProduction/log/pp_TpcReco_$(process).err
Log                = /tmp/pp_TpcReco_match_$(process).log
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 4GB
request_cpus       = 3
Priority           = 20
job_lease_duration = 3600
Arguments          = 10 $(process) 0
Queue 1000