Universe           = vanilla
Initialdir         = /sphenix/user/mitrankova/macros/TpcProduction
Executable         = $(Initialdir)/run_reco.sh
#Output            = /sphenix/user/mitrankova/macros/TpcProduction/log/pp_TpcReco_$(process).out
#Error             = /sphenix/user/mitrankova/macros/TpcProduction/log/pp_TpcReco_$(process).err
Log                = /tmp/poly_pp_TpcReco_$(process).log
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
request_memory     = 8GB
request_cpus       = 3
Priority           = 20
job_lease_duration = 3600
Arguments          = 100 $(process) 0
Queue 100
